name: ans_map_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  geolocator: ^10.0.1
  google_maps_flutter: ^2.3.0
  provider: ^6.0.5
  custom_info_window: ^1.0.1
  http: ^0.13.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/jaha-logo.png
    - assets/bus-stop.png
    - assets/sale-point.png
    - lib/data/bus-stops.json
    - lib/data/sale-points.json
